package com.gl.testngfw.enums;

public enum OEM {
    ACER, ANYDATA, ARCHOS, ASUS, BARNES, BYD, CELLON, CJSC, COMPAL, COOLPAD, DELL, DIGI_IN, DORO, ECS, ENSPERT, FLY,
    FOXCONN, FUHU, FUJITSU, FUJITSU_TEN, FUNAI, GARMIN, GIGABYTE, GIGASET, GOOGLE, HAIER, HISENSE, HP, HTC, HUAWEI,
    INQ, INTEL, IRIVER, JVC, KOBO, KT, KYOCERA, LENOVO, LG, LGE, LUMIGON, MEDIATEK, MICROMAX, MOBIWIRE, MOTOROLA,
    MSI, NEC, NIKON, NVIDIA, OPENPEAK, OPPO, PANASONIC, PANTECH, PEGATRON, PHILIPS, POSITIVO, QUANTA, SAMSUNG,
    SANYO, SEMC, SHARP, SK, SONY, SPICE, SUMITOMO, SYMPHONY, TCT, TECHNICOLOR, TELEEPOCH, TOSHIBA, VERTU, VESTEL,
    VIZIO, WIND, XIAOMI, ZTE
}
